baseURL: https://mujtabot.com
languageCode: en-us
title: Muj on the Internet
theme: ["custom", "hugo-video", "PaperMod"]

# paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Welcome to Mujtaba's online home."
  keywords: [Blog, Portfolio, Newsletter, Books, Learning, Education]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["/muj-on-sup-cropped.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  graphCommentId: "mujtabot"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Muj on the Internet
    # subtitle: "This is subtitle"
    imageUrl: "/muj-on-sup-cropped.jpg"
    imageWidth: 350
    imageHeight: 350
    imageTitle: Muj on SUP
    buttons:
      - name: 🗜️ Projects
        url: p
      - name: 📝 Blog
        url: blog
      - name: 📰 Newsletter
        url: news

  # home-info mode
  homeInfoParams:
    Title: "Muj on the Internet 🚲"
    # Content: Welcome to my blog

  socialIcons:
    - name: Goodreads
      url: "https://www.goodreads.com/user/show/35399941-mujtaba-al-tameemi"
    - name: Telegram
      url: "https://t.me/mujzuh"
    - name: Instagram
      url: "https://instagram.com/muj.living"

  # TODO
  analytics:
    # google:
    #   SiteVerificationTag: "XYZabc"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/mujz/mujtabot.com/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: news
      name: Newsletter
      url: /news/
      weight: 10
    - identifier: projects
      name: Projects
      url: /p/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files
