name = "mujtabot-com"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[env.production]
name = "mujtabot-com-prod"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "29dc"
preview_bucket_name = "29dc"

[env.production.vars]
R2_PUBLIC_URL = "https://files.mujtabot.com"
R2_BUCKET_NAME = "29dc"
# R2 API credentials for presigned URLs - set these as secrets
# R2_ACCESS_KEY_ID = ""
# R2_SECRET_ACCESS_KEY = ""
# R2_ACCOUNT_ID = ""

[env.preview]
name = "mujtabot-com-preview"

[[env.preview.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "29dc"

[env.preview.vars]
R2_PUBLIC_URL = "https://files.mujtabot.com"
R2_BUCKET_NAME = "29dc"
# R2 API credentials for presigned URLs - set these as secrets
# R2_ACCESS_KEY_ID = ""
# R2_SECRET_ACCESS_KEY = ""
# R2_ACCOUNT_ID = "" 